package com.victoryfairy.server.attendance

data class AttendanceLogRequest(
    val date: String? = null,
    val gameDate: String? = null,
    val season: Int,
    val favoriteTeamID: String,
    val opponentTeamID: String,
    val stadiumName: String,
    val result: String,
    val ourScore: Int? = null,
    val opponentScore: Int? = null,
    val favoriteTeamScore: Int? = null,
    val opponentTeamScore: Int? = null,
    val memo: String? = null,
    val shortMemo: String? = null,
    val diaryText: String? = null,
    val seatText: String? = null,
    val companionText: String? = null,
    val companionType: String? = null,
    val highlightTags: List<String> = emptyList(),
    val linkedKBOGameID: String? = null,
    val gameSource: String? = null,
    val sourceLabel: String? = null,
)

data class AttendanceLogDto(
    val id: String,
    val deviceID: String,
    val date: String,
    val gameDate: String,
    val season: Int,
    val favoriteTeamID: String,
    val favoriteTeamName: String,
    val opponentTeamID: String,
    val opponentTeamName: String,
    val stadiumName: String,
    val result: String,
    val ourScore: Int?,
    val opponentScore: Int?,
    val favoriteTeamScore: Int?,
    val opponentTeamScore: Int?,
    val memo: String?,
    val shortMemo: String?,
    val diaryText: String?,
    val seatText: String?,
    val companionText: String?,
    val companionType: String?,
    val highlightTags: List<String>,
    val linkedKBOGameID: String?,
    val gameSource: String?,
    val sourceLabel: String?,
    val sourceDisclosure: String?,
    val photoLocalRefs: List<String>,
    val photoMetadata: List<AttendancePhotoMetadata>,
    val matchupText: String,
    val scoreText: String,
    val createdAt: String,
    val updatedAt: String,
)

data class AttendancePhotoMetadata(
    val id: String,
    val localRef: String,
    val caption: String? = null,
)

data class AttendanceLogListResponse(
    val items: List<AttendanceLogDto>,
    val nextCursor: String? = null,
)
