CREATE TABLE attendance_logs (
    date date NOT NULL,
    opponent_score integer,
    our_score integer,
    season integer NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    id uuid NOT NULL,
    result varchar(20) NOT NULL,
    game_source varchar(30),
    favorite_teamid varchar(60) NOT NULL,
    opponent_teamid varchar(60) NOT NULL,
    linkedkbogameid varchar(80),
    source_label varchar(80),
    companion_text varchar(100),
    seat_text varchar(100),
    stadium_name varchar(100) NOT NULL,
    deviceid varchar(128) NOT NULL,
    memo varchar(300),
    diary_text text,
    highlight_tags_json text,
    CONSTRAINT attendance_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE community_blocks (
    created_at timestamp(6) with time zone,
    id uuid NOT NULL,
    blocked_authorid varchar(80) NOT NULL,
    blocker_deviceid varchar(128) NOT NULL,
    CONSTRAINT community_blocks_pkey PRIMARY KEY (id),
    CONSTRAINT uk_community_blocks_blocker_author UNIQUE (blocker_deviceid, blocked_authorid)
);

CREATE TABLE community_posts (
    like_count integer NOT NULL,
    report_count integer NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    author_display_name varchar(12) NOT NULL,
    id uuid NOT NULL,
    status varchar(20) NOT NULL,
    teamid varchar(60) NOT NULL,
    authorid varchar(80),
    author_deviceid varchar(128) NOT NULL,
    content varchar(300) NOT NULL,
    CONSTRAINT community_posts_pkey PRIMARY KEY (id)
);

CREATE TABLE community_reports (
    created_at timestamp(6) with time zone,
    id uuid NOT NULL,
    postid uuid NOT NULL,
    reason varchar(32) NOT NULL,
    deviceid varchar(128) NOT NULL,
    CONSTRAINT community_reports_pkey PRIMARY KEY (id),
    CONSTRAINT uk_community_reports_post_device UNIQUE (postid, deviceid)
);

CREATE TABLE kbo_games (
    away_score integer,
    date date NOT NULL,
    home_score integer,
    season integer NOT NULL,
    "time" time(6) without time zone,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_at timestamp(6) with time zone NOT NULL,
    status varchar(20) NOT NULL,
    source varchar(30) NOT NULL,
    series_type varchar(40),
    away_teamid varchar(60) NOT NULL,
    home_teamid varchar(60) NOT NULL,
    winner_teamid varchar(60),
    away_team_name varchar(80) NOT NULL,
    gameid varchar(80) NOT NULL,
    home_team_name varchar(80) NOT NULL,
    source_label varchar(80) NOT NULL,
    stadium_name varchar(100) NOT NULL,
    result_summary varchar(200),
    kbo_game_centerurl varchar(500),
    kbo_recordurl varchar(500),
    highlight_tags_json text,
    CONSTRAINT kbo_games_gameid_key UNIQUE (gameid)
);

CREATE TABLE preferences (
    selected_season integer NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    favorite_teamid varchar(60),
    deviceid varchar(128) NOT NULL,
    CONSTRAINT preferences_pkey PRIMARY KEY (deviceid)
);

CREATE TABLE user_profiles (
    created_at timestamp(6) with time zone,
    profile_image_updated_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    nickname varchar(12) NOT NULL,
    id uuid NOT NULL,
    profile_emoji varchar(16),
    favorite_teamid varchar(60) NOT NULL,
    profile_image_mime_type varchar(80),
    public_authorid varchar(80),
    deviceid varchar(128) NOT NULL,
    profile_image_path varchar(160),
    CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_profiles_device UNIQUE (deviceid),
    CONSTRAINT user_profiles_public_authorid_key UNIQUE (public_authorid)
);

CREATE INDEX idx_attendance_date ON attendance_logs (date);
CREATE INDEX idx_attendance_device ON attendance_logs (deviceid);
CREATE INDEX idx_attendance_season ON attendance_logs (season);
CREATE INDEX idx_community_blocks_blocked_author ON community_blocks (blocked_authorid);
CREATE INDEX idx_community_blocks_blocker ON community_blocks (blocker_deviceid);
CREATE INDEX idx_community_posts_author ON community_posts (author_deviceid);
CREATE INDEX idx_community_posts_author_id ON community_posts (authorid);
CREATE INDEX idx_community_posts_status_created ON community_posts (status, created_at);
CREATE INDEX idx_community_posts_team ON community_posts (teamid);
CREATE INDEX idx_community_reports_post ON community_reports (postid);
CREATE INDEX idx_kbo_games_away_team ON kbo_games (away_teamid);
CREATE INDEX idx_kbo_games_date ON kbo_games (date);
CREATE INDEX idx_kbo_games_home_team ON kbo_games (home_teamid);
CREATE INDEX idx_kbo_games_season ON kbo_games (season);
CREATE INDEX idx_kbo_games_source ON kbo_games (source);
CREATE INDEX idx_user_profiles_device ON user_profiles (deviceid);
